name: Post Constitutional Facts to X

on:
  schedule:
    # Post 5 times per day at optimal US engagement times (UTC)
    # 9am EST = 14:00 UTC
    - cron: '0 14 * * *'
    # 12pm EST = 17:00 UTC
    - cron: '0 17 * * *'
    # 3pm EST = 20:00 UTC
    - cron: '0 20 * * *'
    # 6pm EST = 23:00 UTC
    - cron: '0 23 * * *'
    # 9pm EST = 02:00 UTC (next day)
    - cron: '0 2 * * *'

  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  post-fact:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the action to push commits

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install twitter-api-v2 js-yaml

      - name: Post fact to X
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: node scripts/post-fact.js

      - name: Commit updated YAML
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/constitutional-facts.yaml
          git diff --quiet && git diff --staged --quiet || git commit -m "Mark fact as posted [skip ci]"
          git push
