name: Post Daily Constitution Answer

on:
  schedule:
    # Runs at 1:00 PM EST (18:00 UTC) every day - 1 hour after question
    - cron: '0 18 * * *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  post-answer:
    runs-on: ubuntu-latest
    steps:
      - name: Post answer to X
        run: |
          curl -X POST https://constitution-compass.vercel.app/api/post-daily-answer \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -v
